server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:8761/eurake
  server:
    renewal-percent-threshold: 0.45
  instance:
    hostname: localhost
spring:
  security:
    user:
      name: root
      password: 123456